version: '3.8'

services:
  trading-bot:
    build: .
    container_name: kraken-lumibot
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    env_file:
      - .env
    environment:
      # API Credentials
      - KRAKEN_API_KEY=your_api_key_here
      - KRAKEN_API_SECRET=your_api_secret_here
      
      # Trading Parameters
      - TRADING_SYMBOL=X:BTCUSD
      - POSITION_SIZE_PERCENTAGE=0.1
      - MIN_CASH_BALANCE=10
      
      # Technical Indicators
      - RSI_PERIOD=14
      - BB_PERIOD=20
      - BB_STD_DEV=2
      - SMA_PERIOD=20
      
      # Time Settings
      - TZ=UTC
      - SLEEP_TIME=30M
      - PYTHONUNBUFFERED=1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 